### ISSUE TITLE
Link to Together AI broken?

### ISSUE THREAD

**Issue by AlexSchuckert** [WilliamKeating/obsidian-autocorrect#1]
Hello, thanks for creating this! 

I have tried to install this plugin, but I couldn't get it to work. I always get "Error correcting spelling. Make sure API key is correct and Internet is working." Weirdly, I do see 100% successful requests to mistral on together.ai. I have added the API key, I have credit and I have added a credit card to enable 600 rpm. I have installed the plugin manually by copy-pasting the release into the plugins folder of obsidian. I use MacOS 15.2.

Does the usage of together.ai maybe somehow need to be updated?

Thank you!

**Comment by WilliamKeating** [comment]
Hi Alex,

I’m happy to hear you’re interested in using this—sorry it’s been so challenging. It looks like the LLM was formatting its responses in an unexpected way that the code couldn’t parse. (I have no idea why it worked previously and no longer does. My best guess is that Together.ai updated the model weights, but that seems unlikely.)

I haven’t actively maintained this plugin, and a _lot_ has changed in the LLM space in the past year. It seems that Groq.com is now the best option for LLM inference for this use case, offering significantly lower latency than any other option on the market and a very generous free tier (whearas it looks like Together.ai has now reduced their free credits to $1). I took this as an opportunity to transition the plugin to Groq and replace the model with the current state-of-the-art for latency-to-performance: Llama 3.3 70b.

Thanks for reaching out—please let me know if this ends up working for you.

**Comment by AlexSchuckert** [comment]
Hi William,

Thank you so much for releasing another version of this so incredibly fast! It now works perfectly and it almost feels like magic. I hope more people will use this as the missing autocorrect on obsidian on Mac is something that a lot of people have complained about.

Awesome work thank you!
